spring:
  redis:
    host: ${REDIS_HOST:localhost}
  
aws:
  dynamodb:
    endpoint: http://localhost:4566
  s3:
    endpoint: http://localhost:4566
  accessKeyId: test
  secretAccessKey: test

logging:
  level:
    com.mastercard.enrichment: DEBUG
    software.amazon.awssdk: DEBUG
